# Generated by Django 2.2 on 2019-05-13 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('password', models.TextField(blank=True)),
                ('is_admin', models.BooleanField()),
                ('points', models.IntegerField()),
                ('avatar', models.TextField(blank=True)),
                ('belongs_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='households.Household')),
            ],
        ),
    ]
