# Generated by Django 2.2 on 2019-05-13 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('isAllDay', models.BooleanField()),
                ('points', models.IntegerField()),
                ('status', models.IntegerField()),
                ('recurrence_pattern', models.IntegerField()),
                ('recurrence_enddate', models.DateTimeField(null=True)),
                ('deadline', models.DateTimeField()),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chores_assigned', to='users.User')),
                ('belongs_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chores', to='households.Household')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chores_created', to='users.User')),
            ],
        ),
    ]
